### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by SugarMasuo** [sagniklp/dewarpnet-demo#1]
Hi, thank you for sharing. When I upload a image, click 'unwarp', no output

**Comment by sagniklp** [comment]
Thank you for notifying me! It's back up now.

**Comment by SugarMasuo** [comment]
![image](https://user-images.githubusercontent.com/15923907/66825368-b8fbbe80-ef7c-11e9-98fe-9fabe7ac8267.png)
 I still fail, did I open it the wrong way

**Comment by sagniklp** [comment]
Its working for me. Could you see the browser console and tell me if some
errors are popping up?

Sagnik Das

**Comment by SugarMasuo** [comment]
It's OK for me sometime and sometime not.
I did some test as following: 
Perspective:
![image](https://user-images.githubusercontent.com/15923907/66970213-3b8c9700-f0bf-11e9-9875-3bb8e020f2a2.png)

curled:
![image](https://user-images.githubusercontent.com/15923907/66970539-793def80-f0c0-11e9-81d1-6612797d0bd2.png)

two-pages:
![image](https://user-images.githubusercontent.com/15923907/66970408-06347900-f0c0-11e9-9406-e6bc7930112b.png)

**Comment by sagniklp** [comment]
Two-page case will not work properly due to the white edges (thickness) of the book. You can see the segmentation is that good in that case! Also, the current model is not trained with such book examples. 
**Tips:**
- Always try to do a tight crop of the document, leaving too much background on the sides will break the model.
- Try to keep the entire document in the input image.

**Regarding the shape of the unwarped document:**
The network doesn't know the real aspect ratio of the paper, so the unwarped image will have a shape of the input image.

**Comment by SugarMasuo** [comment]
> **Regarding the shape of the unwarped document:**
> The network doesn't know the real aspect ratio of the paper, so the unwarped image will have a shape of the input image.

Yes! I also think that is the point, so unwarp of the samples with perspective transformation is more difficult than just curled ones in this model, right?

**Comment by SugarMasuo** [comment]
> You can see the segmentation is that good in that case!

the segmentation is good! But it is difficult to visually see the 3d coordinate recovery is right or wrong from the color image, do you have any tips?

**Comment by sagniklp** [comment]
I

> > **Regarding the shape of the unwarped document:**
> > The network doesn't know the real aspect ratio of the paper, so the unwarped image will have a shape of the input image.
> 
> Yes! I also think that is the point, so unwarp of the samples with perspective transformation is more difficult than just curled ones in this model, right?

No, we can't really say that. You just have to fix the aspect ratio after unwarping. Recovering the shape of the paper is not modeled. 
Moreover, if the camera angle is too skewed (due to perspective) the sampling won't be good. You can't sample more pixels than visible.

**Comment by sagniklp** [comment]
> > You can see the segmentation is that good in that case!
> 
> the segmentation is good! But it is difficult to visually see the 3d coordinate recovery is right or wrong from the color image, do you have any tips?

In the book case the segmentation in broken on the edges, that's what I meant. If the segmentation is not good the texture regression network suffers from that error. 

To understand the 3D shape you should look for dark and light areas. Dark means closer to zero, or higher depth. Lighter means closer to one, or lower depth.

**Comment by SugarMasuo** [comment]
> * Always try to do a tight crop of the document, leaving too much background on the sides will break the model.

Hello, according to this principle, should we do crop after reading images like this,
![image](https://user-images.githubusercontent.com/15923907/67366637-73577b00-f5a6-11e9-8907-4a4e72217c4f.png)
![image](https://user-images.githubusercontent.com/15923907/67366647-79e5f280-f5a6-11e9-89c3-256cdd327ded.png)
or just put the 448*448 image as input?

**Comment by sagniklp** [comment]
Yes, crop it!
