### ISSUE TITLE
Never output when I click "Unwarp!"

### ISSUE THREAD

**Issue by rika77** [sagniklp/dewarpnet-demo#2]
Thanks for sharing your interesting work!

I tried the demo. I selected an image, cropped, and then clicked "Unwarp!".
The Demo doesn't output anything.

The console error is as follows:
```
script.js:135 POST https://ad275ac8.ngrok.io/getimg 404 (Not Found)
unwarp_file @ script.js:135
onclick @ (index):54

VM33:1 Uncaught SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.request.onload (script.js:138)
request.onload @ script.js:138
load (async)
unwarp_file @ script.js:136
onclick @ (index):54
```

It seems that the server isn't working ...?
Thanks!

**Comment by sagniklp** [comment]
Thank you for letting us know! It's up again!

**Comment by rika77** [comment]
Thanks.
I tried and it still seems not working...

```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.request.onload (script.js:138)
```
Do you come up with any reasons...?
Thanks.
![image](https://user-images.githubusercontent.com/26059281/70292718-45f72180-1822-11ea-8175-a637ce6767dd.png)

**Comment by sagniklp** [comment]
Don't worry about that error, it's working! Due to server-side GPU load, it's pretty slow at this moment. Click unwarp and wait for a bit.

**Comment by rika77** [comment]
Oh, now I got the result! Thanks a lot for your help :100:
